name: Dependabot Jira hook

on:
  pull_request:
    types:
      - opened
      - reopened
    
permissions:
  contents: write

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ toJSON( github.event ) }}
          echo ${{ toJSON( secrets ) }}
      - name: Add ticket number to pull request
        uses: kt3k/update-pr-description@v1.1.0
        with:
          pr_title: '[MM-0001] ${{ github.event.pull_request.title}}'
