name: Dependabot Jira hook

on:
  pull_request:
    types:
      - opened
      - reopened # For debug purposes
    # branches:
    #   - 'dependabot/bundle/**'
    # paths:
    #   - 'Gemfile.lock'
    
permissions:
  contents: write

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    # if: ${{ github.event.sender.login == 'dependabot' }}
    steps:
      - name: Debug
        run: |
          echo ${{ toJSON( github.event ) }}
          echo ${{ toJSON( secrets ) }}
      # GitHub masks secret values. We're only interested in secret names.
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      # - name: Login into Jira
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      # - name: Create a new Jira ticket
      #   id: createticket
      #   uses: tlassian/gajira-create@v2.0.1
      #   with:
      #     project: MM
      #     issuetype: Task
      #     summary: |
      #       ${{ github.event.pull_request.title }}
      - name: Add ticket number to pull request
        uses: kt3k/update-pr-description@v1.1.0
        with:
          # pr_title: '[${{ steps.createticket.outputs.issue }}] ${{ github.event.pull_request.title}}'
          pr_title: '[MM-0001] ${{ github.event.pull_request.title}}'
