name: Dependabot Jira hook

on:
  pull_request:
    types:
      - opened
      - reopened
    
permissions:
  contents: write

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: lhotari/action-upterm@v1
        with:
          limit-access-to-actor: true
      - run: echo "${{ toJSON( github.event ) }}"
      - run: echo "${{ toJSON( secrets ) }}"
      - name: Add ticket number to pull request
        uses:  yevhenii-ponomarenko/update-pr-description@v2.1.0
        with:
          pr_title: '[MM-0001] ${{ github.event.pull_request.title }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: main
